MAX_COOCKING_TIME = 720
MIN_COOCKING_TIME = 1

MAX_INGREDIENT_AMOUNT = 5000
MIN_INGREDIENT_AMOUNT = 1

MAX_LENGTH_DEFAULT = 32
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_RECIPE_NAME = 256
MAX_LENGTH_INGREDIENT_UNIT = 64

MAX_LENGTH_USER_NAME = 150
MAX_LENGTH_EMAIL = 254
