volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:17.2
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - static:/backend_static
      - media:/mediafiles
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./gateway/
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/mediafiles
