# Generated by Django 5.1.4 on 2025-01-10 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_shoppinglist_options_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_resipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
