# Generated by Django 5.1.4 on 2025-01-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredientinrecipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_hash',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
